openapi: 3.0.1
info:
  title: API Manager REST Actions Events API
  description: The API Manager REST API is used by the API Manager UI to get stuff done. You can use it to automate any API Management task you wish. For example, create new Organizations, Plans, Clients, and APIs.
  version: 3.1.0-SNAPSHOT
servers:
- url: /apiman
tags:
- name: Events
paths:
  /events/sso/users:
    post:
      tags:
      - Events
      operationId: newAccountCreated
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAccountCreatedDto'
      responses:
        default:
          description: default response
          content:
            '*/*': {}
components:
  schemas:
    NewAccountCreatedDto:
      type: object
      properties:
        time:
          type: string
          format: date-time
        userId:
          type: string
        username:
          type: string
        emailAddress:
          type: string
        firstName:
          type: string
        surname:
          type: string
        roles:
          uniqueItems: true
          type: array
          items:
            type: string
        attributes:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        approvalRequired:
          type: boolean
